- name: Install Apache2
  hosts: [app]
  become: yes

  tasks:
    - name: Ensure apt package manager is updated
      apt: update_cache=yes

    - name: Install Apache2
      apt: name=apache2 state=present

    - name: Start Apache2 service
      service: name=apache2 state=started