---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ABT-Main-Key"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{iam_access_key}}"  # From vault as defined
      aws_secret_key: "{{iam_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0dee22c13ea7a9a67", name: "Ubuntu-Node-1" }
      - { image: "ami-0dee22c13ea7a9a67", name: "Ubuntu-Node-2" }
