---
- hosts: all
  become: true

  tasks:
    - name: Shutdown all Ubuntu instances only
      ansible.builtin.command: /sbin/shutdown -t now
      when:
        ansible_facts['os_family'] == "Debian"
