---
- hosts: all
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist-upgrade
        state: latest
